version: '3'

networks:
  traefik:
  internal:

services:
  # Monitoring server
  prometheus:
    image: prom/prometheus
    expose:
      - 9090
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      - traefik.http.routers.prometheus.rule=Host(`prometheus.lan`)
      - traefik.entryPoints.prometheus.address=9090
    networks:
      - traefik

  # Monitoring node service
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.conntrack'
      - "--collector.diskstats"
      - "--collector.entropy"
      - "--collector.filefd"
      - "--collector.systemd"
      - "--collector.processes"
      - "--collector.filesystem"
      - "--collector.loadavg"
      - "--collector.mdadm"
      - "--collector.meminfo"
      - "--collector.netdev"
      - "--collector.netstat"
      - "--collector.stat"
      - "--collector.textfile"
      - "--collector.time"
      - "--collector.vmstat"
      - "--collector.ipvs"
    labels:
      - traefik.enable=false
    networks:
      - traefik

  # Dashboards
  grafana:
    image: grafana/grafana:7.2.0
    expose:
      - 3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    user: "1000" # current user
    labels:
      - traefik.http.routers.grafana.rule=Host(`grafana.lan`)
    networks:
      - traefik

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.3
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8181:8080"
      # HTTPS
      - "443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

